In [3]:
import pandas as pd
import numpy as np
from sklearn import decomposition
import matplotlib.pyplot as plt

In [4]:
dataset = pd.read_csv("raw.csv")

In [5]:
data = dataset.iloc[:,:].values
label = dataset.iloc[:,-1].values
len(data[0])

39

In [6]:
dataset.iloc[:,14:38]

can work long time before system? self-learning capability?  \
0                                   yes                       yes   
1                                   yes                        no   
2                                   yes                        no   
3                                    no                       yes   
4                                    no                        no   
5                                   yes                       yes   
6                                    no                        no   
7                                   yes                        no   
8                                    no                       yes   
9                                    no                        no   
10                                  yes                        no   
11                                   no                       yes   
12                                  yes                        no   
13                                   no                        no   
14                                  yes                        no   
15                                  yes                       yes   
16                                   no                        no   
17                                   no                       yes   
18                                   no                        no   
19                                   no                       yes   
20                                  yes                       yes   
21                                  yes                       yes   
22                                   no                        no   
23                                   no                       yes   
24                                  yes                       yes   
25                                  yes                       yes   
26                                   no                       yes   
27                                  yes                       yes   
28                                  yes                        no   
29                                  yes                        no   
...                                 ...                       ...   
19970                               yes                       yes   
19971                                no                       yes   
19972                                no                       yes   
19973                                no                       yes   
19974                                no                        no   
19975                                no                        no   
19976                                no                        no   
19977                                no                       yes   
19978                               yes                        no   
19979                                no                        no   
19980                               yes                        no   
19981                                no                       yes   
19982                               yes                        no   
19983                                no                        no   
19984                                no                        no   
19985                               yes                       yes   
19986                                no                       yes   
19987                                no                        no   
19988                               yes                        no   
19989                               yes                        no   
19990                                no                        no   
19991                                no                       yes   
19992                               yes                        no   
19993                                no                        no   
19994                                no                       yes   
19995                               yes                        no   
1999

In [7]:
dataset.iloc[:,:14]

Acedamic percentage in Operating Systems  percentage in Algorithms  \
0                                            69                        63   
1                                            78                        62   
2                                            71                        86   
3                                            76                        87   
4                                            92                        62   
5                                            88                        86   
6                                            93                        77   
7                                            84                        72   
8                                            73                        66   
9                                            62                        76   
10                                           73                        80   
11                                           63                        76   
12                                           63                        64   
13                                           68                        93   
14                                           90                        83   
15                                           94                        71   
16                                           60                        92   
17                                           92                        86   
18                                           82                        91   
19                                           90                        73   
20                                           67                        61   
21                                           65                        61   
22                                           84                        62   
23                                           74                        89   
24                                           92                        67   
25                                           75                        74   
26                                           90                        82   
27                                           71                        60   
28                                           83                        82   
29                                           83                        68   
...                                         ...                       ...   
19970                                        65                        84   
19971                                        88                        92   
19972                                        64                        74   
19973                                        64                        66   
19974                                        68                        61   
19975                                        84                        68   
19976                                        67                        69   
19977                                        88                        71   
19978                                        71                        73   
19979                                        60                        77   
19980                                        78                        64   
19981                                        80                        89   
19982                                        64                        94   
19983                                        80                        92   
19984                                        72                        69   
19985                                        65                        77   
19986                                        74                        72   
19987                                        82                        62   
19988                                        64                        85   
19989                                        73                        60   
199

In [8]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [9]:
labelencoder = LabelEncoder()

In [10]:
for i in range(14,38):
    data[:,i] = labelencoder.fit_transform(data[:,i])
data[:5]

array([[69, 63, 78, 87, 94, 94, 87, 84, 61, 9, 4, 0, 4, 8, 1, 1, 1, 8, 0,
        0, 1, 0, 0, 4, 4, 0, 8, 0, 0, 21, 1, 0, 1, 0, 0, 0, 1, 0,
        'Database Developer'],
       [78, 62, 73, 60, 71, 70, 73, 84, 91, 12, 7, 1, 2, 3, 1, 0, 1, 5,
        2, 0, 0, 2, 1, 7, 0, 1, 4, 1, 1, 5, 1, 1, 0, 1, 0, 0, 0, 1,
        'Portal Administrator'],
       [71, 86, 91, 87, 61, 81, 72, 72, 94, 11, 1, 4, 1, 3, 1, 0, 1, 0,
        7, 0, 1, 2, 0, 6, 2, 0, 5, 1, 1, 29, 0, 0, 1, 0, 1, 0, 0, 1,
        'Portal Administrator'],
       [76, 87, 60, 84, 89, 73, 62, 88, 69, 7, 1, 1, 2, 5, 0, 1, 0, 6, 1,
        1, 0, 1, 0, 7, 5, 0, 7, 0, 0, 23, 0, 1, 0, 0, 1, 1, 1, 1,
        'Systems Security Administrator'],
       [92, 62, 90, 67, 71, 89, 73, 71, 73, 4, 5, 4, 6, 3, 0, 0, 0, 0, 0,
        0, 0, 2, 0, 0, 5, 0, 9, 0, 1, 7, 1, 0, 1, 0, 1, 0, 1, 1,
        'Business Systems Analyst']], dtype=object)

In [11]:
data[:5,14:]

array([[1, 1, 1, 8, 0, 0, 1, 0, 0, 4, 4, 0, 8, 0, 0, 21, 1, 0, 1, 0, 0,
        0, 1, 0, 'Database Developer'],
       [1, 0, 1, 5, 2, 0, 0, 2, 1, 7, 0, 1, 4, 1, 1, 5, 1, 1, 0, 1, 0, 0,
        0, 1, 'Portal Administrator'],
       [1, 0, 1, 0, 7, 0, 1, 2, 0, 6, 2, 0, 5, 1, 1, 29, 0, 0, 1, 0, 1,
        0, 0, 1, 'Portal Administrator'],
       [0, 1, 0, 6, 1, 1, 0, 1, 0, 7, 5, 0, 7, 0, 0, 23, 0, 1, 0, 0, 1,
        1, 1, 1, 'Systems Security Administrator'],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 5, 0, 9, 0, 1, 7, 1, 0, 1, 0, 1, 0,
        1, 1, 'Business Systems Analyst']], dtype=object)

In [12]:
from sklearn.preprocessing import Normalizer

In [13]:
data1=data[:,:14]

In [14]:
normalized_data = Normalizer().fit_transform(data1)
print(normalized_data.shape)

(20000, 14)


In [15]:
data2=data[:,14:39]

In [16]:
df1 = np.append(normalized_data,data2,axis=1)

In [17]:
X1 = pd.DataFrame(df1,columns=['Acedamic percentage in Operating Systems', 'percentage in Algorithms',
       'Percentage in Programming Concepts',
       'Percentage in Software Engineering', 'Percentage in Computer Networks',
       'Percentage in Electronics Subjects',
       'Percentage in Computer Architecture', 'Percentage in Mathematics',
       'Percentage in Communication skills', 'Hours working per day',
       'Logical quotient rating', 'hackathons', 'coding skills rating',
       'public speaking points', 'can work long time before system?',
       'self-learning capability?', 'Extra-courses did', 'certifications',
       'workshops', 'talenttests taken?', 'olympiads',
       'reading and writing skills', 'memory capability score',
       'Interested subjects', 'interested career area ', 'Job/Higher Studies?',
       'Type of company want to settle in?',
       'Taken inputs from seniors or elders', 'interested in games',
       'Interested Type of Books', 'Salary Range Expected',
       'In a Realtionship?', 'Gentle or Tuff behaviour?',
       'Management or Technical', 'Salary/work', 'hard/smart worker',
       'worked in teams ever?', 'Introvert','Suggested Job Role'])

In [18]:
X1.head()


Acedamic percentage in Operating Systems percentage in Algorithms  \
0                                  0.28509                 0.260299   
1                                  0.34998                 0.278189   
2                                 0.295012                 0.357339   
3                                 0.328025                 0.375503   
4                                 0.397157                 0.267649   

  Percentage in Programming Concepts Percentage in Software Engineering  \
0                           0.322276                           0.359461   
1                           0.327545                           0.269215   
2                           0.378115                           0.361494   
3                           0.258967                           0.362554   
4                           0.388523                           0.289234   

  Percentage in Computer Networks Percentage in Electronics Subjects  \
0                        0.388383                           0.388383   
1                        0.318571                           0.314085   
2                        0.253461                           0.336563   
3                        0.384135                           0.315077   
4                        0.306502                           0.384206   

  Percentage in Computer Architecture Percentage in Mathematics  \
0                            0.359461                  0.347066   
1                            0.327545                  0.376901   
2                            0.299168                  0.299168   
3                              0.2676                  0.379819   
4                            0.315136                  0.306502   

  Percentage in Communication skills Hours working per day  \
0                           0.252036             0.0371856   
1                            0.40831             0.0538431   
2                            0.39058             0.0457062   
3                           0.297812             0.0302129   
4                           0.315136             0.0172677   

                ...               Interested Type of Books  \
0               ...                                     21   
1               ...                                      5   
2               ...                                     29   
3               ...                                     23   
4               ...                                      7   

  Salary Range Expected In a Realtionship? Gentle or Tuff behaviour?  \
0                     1                  0                         1   
1                     1                  1                         0   
2                     0                  0                         1   
3                     0                  1                         0   
4                     1                  0                         1   

  Management or Technical Salary/work hard/smart worker worked in teams ever?  \
0                       0           0                 0                     1   
1                       1           0                 0                     0   
2                       0           1                 0                     0   
3                       0           1                 1                     1   
4                       0           1                 0                     1   

  Introvert              Suggested Job Role  
0         0              Database Developer  
1         1            Portal Administrator  
2         1            Portal Administrator  
3         1  Systems Security Administrator  
4         1        Business Systems Analyst  

[5 rows x 39 columns]

In [19]:
array = X1.values


In [26]:
X = array[:,0:38]
X[5,28]

1

In [27]:
Y = array[:,38]


In [69]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [70]:
test = SelectKBest(score_func=chi2, k=10)
fit = test.fit(X, Y)

In [71]:
np.set_printoptions(suppress=True)

In [72]:
print(fit.scores_)

[  0.07731139   0.12855032   0.21548332   0.2126444    0.14255932
   0.21168552   0.06594597   0.13359824   0.12469917   0.13067329
   0.22122457   0.24264637   0.17045649   0.26406684  14.41780905
  17.25196111  14.66796188  54.18460314  41.34135698  18.01280881
  12.62565512  26.28728852  13.0853429   42.3386115   31.7413281
  13.65271667  68.91647142  24.09236349  18.87149223 177.70920787
  20.403078    22.08639665  15.64471174  20.55506163  17.13628154
  23.75150984  19.59951792  16.67365107]


In [73]:
features = fit.transform(X)

In [74]:
print(features[0:5,:])

[[ 8.  0.  0.  4.  4.  8.  0. 21.  0.  0.]
 [ 5.  2.  2.  7.  0.  4.  1.  5.  1.  0.]
 [ 0.  7.  2.  6.  2.  5.  1. 29.  0.  0.]
 [ 6.  1.  1.  7.  5.  7.  0. 23.  1.  1.]
 [ 0.  0.  2.  0.  5.  9.  0.  7.  0.  0.]]


In [75]:
label = labelencoder.fit_transform(label)
print(len(label))

20000


In [24]:
y=pd.DataFrame(label,columns=["Suggested Job Role"])
y.head()
y

Suggested Job Role
0                             Database Developer
1                           Portal Administrator
2                           Portal Administrator
3                 Systems Security Administrator
4                       Business Systems Analyst
5                      Software Systems Engineer
6                             Database Developer
7                  Business Intelligence Analyst
8                       Business Systems Analyst
9                        CRM Technical Developer
10                 Mobile Applications Developer
11                                   UX Designer
12                       CRM Technical Developer
13                      Business Systems Analyst
14                   Quality Assurance Associate
15                                 Web Developer
16                                 Web Developer
17                  Information Security Analyst
18                          CRM Business Analyst
19                  Information Security Analyst
20                            Database Developer
21                      Business Systems Analyst
22                   Quality Assurance Associate
23                             Technical Support
24                             Technical Support
25                  Information Security Analyst
26                 Business Intelligence Analyst
27                               Project Manager
28                Information Technology Manager
29                                 Web Developer
...                                          ...
19970              Business Intelligence Analyst
19971              Mobile Applications Developer
19972                         Programmer Analyst
19973             Information Technology Manager
19974                         E-Commerce Analyst
19975                         Software Developer
19976                            Project Manager
19977                       Portal Administrator
19978                          Software Engineer
19979                   Business Systems Analyst
19980                          Software Engineer
19981                     Applications Developer
19982               Information Security Analyst
19983                           Database Manager
19984                         Technical Engineer
19985                        Solutions Architect
19986             Information Technology Manager
19987              Business Intelligence Analyst
19988                              Web Developer
19989                         Programmer Analyst
19990                              Web Developer
19991             Information Technology Manager
19992                          Technical Support
19993                  Software Systems Engineer
19994                          Software Engineer
19995                         Technical Engineer
19996                         E-Commerce Analyst
19997              Business Intelligence Analyst
19998  Software Quality Assurance (QA) / Testing
19999                     Applications Developer

[20000 rows x 1 columns]

In [79]:
data3 = dataset.iloc[:,:-1].values
label3 = dataset.iloc[:,-1].values
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()

for i in range(14,38):
    data3[:,i] = labelencoder.fit_transform(data3[:,i])
    
from sklearn.preprocessing import Normalizer
data4=data3[:,:14]

normalized_data1 = Normalizer().fit_transform(data1)
data5=data3[:,14:]

df5 = np.append(normalized_data1,data5,axis=1)

In [80]:

Z= pd.DataFrame(df5,columns=['Acedamic percentage in Operating Systems', 'percentage in Algorithms',
       'Percentage in Programming Concepts',
       'Percentage in Software Engineering', 'Percentage in Computer Networks',
       'Percentage in Electronics Subjects',
       'Percentage in Computer Architecture', 'Percentage in Mathematics',
       'Percentage in Communication skills', 'Hours working per day',
       'Logical quotient rating', 'hackathons', 'coding skills rating',
       'public speaking points', 'can work long time before system?',
       'self-learning capability?', 'Extra-courses did', 'certifications',
       'workshops', 'talenttests taken?', 'olympiads',
       'reading and writing skills', 'memory capability score',
       'Interested subjects', 'interested career area ', 'Job/Higher Studies?',
       'Type of company want to settle in?',
       'Taken inputs from seniors or elders', 'interested in games',
       'Interested Type of Books', 'Salary Range Expected',
       'In a Realtionship?', 'Gentle or Tuff behaviour?',
       'Management or Technical', 'Salary/work', 'hard/smart worker',
       'worked in teams ever?', 'Introvert'])

In [81]:
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn import preprocessing 
from sklearn.metrics import accuracy_score

In [82]:
X_train,X_test,y_train,y_test=train_test_split(Z,y,test_size=0.2,random_state=10)

In [83]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

In [84]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [85]:
y_pred = clf.predict(X_test)

In [86]:
y_pred


array([20,  6, 15, ..., 14, 28, 28], dtype=int64)

In [87]:
cm = confusion_matrix(y_test,y_pred)
accuracy = accuracy_score(y_test,y_pred)

In [88]:
print("confusion matrics=",cm)
print("  ")
print("accuracy=",accuracy*100)

confusion matrics= [[4 7 2 ... 5 4 1]
 [4 1 1 ... 2 3 2]
 [1 1 3 ... 4 1 6]
 ...
 [4 2 2 ... 4 2 4]
 [4 3 2 ... 5 5 7]
 [2 4 1 ... 4 2 1]]
  
accuracy= 2.6


In [89]:
 #Decision tree with entropy
    
clf_entropy = tree.DecisionTreeClassifier(criterion = "entropy", random_state = 10)
clf_entropy.fit(X_train, y_train)
    

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=10,
            splitter='best')

In [90]:

entropy_y_pred=clf_entropy.predict(X_test)

In [91]:
cm_entopy = confusion_matrix(y_test,entropy_y_pred)

In [92]:
entropy_accuracy = accuracy_score(y_test,entropy_y_pred)
print("confusion matrics=",cm_entopy)
print("  ")
print("accuracy=",entropy_accuracy*100)

confusion matrics= [[1 3 7 ... 3 2 2]
 [2 4 3 ... 3 2 4]
 [1 2 4 ... 0 3 1]
 ...
 [1 6 3 ... 0 5 2]
 [3 2 4 ... 2 2 4]
 [5 1 6 ... 6 6 4]]
  
accuracy= 2.7


In [93]:
#SVM (Support vector machine) classifier


from sklearn import svm

In [96]:
clf = svm.SVC()
clf.fit(X_train, y_train)

C:\Users\Appu\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [97]:
svm_y_pred = clf.predict(X_test)

In [98]:
svm_cm = confusion_matrix(y_test,svm_y_pred)
svm_accuracy = accuracy_score(y_test,svm_y_pred)

In [99]:

print("confusion matrics=",svm_cm)
print("  ")
print("accuracy=",svm_accuracy*100)

confusion matrics= [[0 0 1 ... 1 1 0]
 [0 0 4 ... 0 0 0]
 [1 0 2 ... 0 0 0]
 ...
 [0 0 1 ... 0 1 0]
 [0 0 2 ... 0 0 0]
 [0 1 2 ... 0 1 0]]
  
accuracy= 5.175


In [102]:
#XG Boost

X_train,X_test,y_train,y_test=train_test_split(Z,y,test_size=0.3,random_state=10)

In [103]:
X_train.shape

(14000, 38)

In [104]:
X_train=pd.to_numeric(X_train.values.flatten())

In [109]:
X_train=X_train.reshape((14000,38))

In [112]:
from xgboost import XGBClassifier

In [113]:
model = XGBClassifier()
model.fit(X_train, y_train)

C:\Users\Appu\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:95: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  encode : bool, default False
C:\Users\Appu\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:128: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  the valid values.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='multi:softprob', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [114]:
xgb_y_pred = clf.predict(X_test)

In [115]:
xgb_cm = confusion_matrix(y_test,xgb_y_pred)
xgb_accuracy = accuracy_score(y_test,xgb_y_pred)

In [116]:
print("confusion matrics=",xgb_cm)
print("  ")
print("accuracy=",xgb_accuracy*100)

confusion matrics= [[1 0 1 ... 1 1 0]
 [1 0 4 ... 0 0 0]
 [1 0 7 ... 2 0 0]
 ...
 [0 0 1 ... 2 1 0]
 [0 0 2 ... 0 3 0]
 [0 1 3 ... 0 1 0]]
  
accuracy= 6.966666666666667
