In [1]:
import pandas as pd
import numpy as np
from sklearn import decomposition
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv("row_data.csv")

In [3]:
dataset


Acedamic percentage in Operating Systems  percentage in Algorithms  \
0                                            69                        63   
1                                            78                        62   
2                                            71                        86   
3                                            76                        87   
4                                            92                        62   
5                                            88                        86   
6                                            93                        77   
7                                            84                        72   
8                                            73                        66   
9                                            62                        76   
10                                           73                        80   
11                                           63                        76   
12                                           63                        64   
13                                           68                        93   
14                                           90                        83   
15                                           94                        71   
16                                           60                        92   
17                                           92                        86   
18                                           82                        91   
19                                           90                        73   
20                                           67                        61   
21                                           65                        61   
22                                           84                        62   
23                                           74                        89   
24                                           92                        67   
25                                           75                        74   
26                                           90                        82   
27                                           71                        60   
28                                           83                        82   
29                                           83                        68   
...                                         ...                       ...   
19970                                        65                        84   
19971                                        88                        92   
19972                                        64                        74   
19973                                        64                        66   
19974                                        68                        61   
19975                                        84                        68   
19976                                        67                        69   
19977                                        88                        71   
19978                                        71                        73   
19979                                        60                        77   
19980                                        78                        64   
19981                                        80                        89   
19982                                        64                        94   
19983                                        80                        92   
19984                                        72                        69   
19985                                        65                        77   
19986                                        74                        72   
19987                                        82                        62   
19988                                        64                        85   
19989                                        73                        60   
199

# Exploratory Data Analysis

In [4]:
dataset.describe() 


Acedamic percentage in Operating Systems  percentage in Algorithms  \
count                              20000.000000              20000.000000   
mean                                  77.002300                 76.948200   
std                                   10.085697                 10.101733   
min                                   60.000000                 60.000000   
25%                                   68.000000                 68.000000   
50%                                   77.000000                 77.000000   
75%                                   86.000000                 86.000000   
max                                   94.000000                 94.000000   

       Percentage in Programming Concepts  Percentage in Software Engineering  \
count                        20000.000000                        20000.000000   
mean                            77.017550                           77.094500   
std                             10.134815                           10.087837   
min                             60.000000                           60.000000   
25%                             68.000000                           68.000000   
50%                             77.000000                           77.000000   
75%                             86.000000                           86.000000   
max                             94.000000                           94.000000   

       Percentage in Computer Networks  Percentage in Electronics Subjects  \
count                     20000.000000                        20000.000000   
mean                         76.958200                           77.015550   
std                          10.020088                           10.168888   
min                          60.000000                           60.000000   
25%                          68.000000                           68.000000   
50%                          77.000000                           77.000000   
75%                          85.000000                           86.000000   
max                          94.000000                           94.000000   

       Percentage in Computer Architecture  Percentage in Mathematics  \
count                         20000.000000               20000.000000   
mean                             77.069850                  76.913100   
std                              10.069059                  10.138555   
min                              60.000000                  60.000000   
25%                              68.000000                  68.000000   
50%                              77.000000                  77.000000   
75%                              86.000000                  86.000000   
max                              94.000000                  94.000000   

       Percentage in Communication skills  Hours working per day  \
count                        20000.000000           20000.000000   
mean                            76.921450               7.985950   
std                             10.103494               2.593798   
min                             60.000000               4.000000   
25%                             68.000000               6.000000   
50%                             77.000000               8.000000   
75%                             86.000000              10.000000   
max                             94.000000              12.000000   

       Logical quotient rating    hackathons  coding skills rating  \
count             20000.000000  20000.000000          20000.000000   
mean                  4.995050      2.992650              5.004750   
std                   2.578383      2.005791              2.576831   
min                   1.000000      0.000000              1.000000   
25%                   3.000000      1.000000              3.000000   
50%                   5.000000      3.000000              5.000000   
75%                   7.000000      5.000000              7.000000   
max                   9.000000      6.000000     

In [5]:
data = dataset.iloc[:,:].values
label = dataset.iloc[:,-1].values

In [6]:
data

array([[69, 63, 78, ..., 'yes', 'no', 'Database Developer'],
       [78, 62, 73, ..., 'no', 'yes', 'Portal Administrator'],
       [71, 86, 91, ..., 'no', 'yes', 'Portal Administrator'],
       ...,
       [83, 70, 80, ..., 'no', 'yes', 'Business Intelligence Analyst'],
       [68, 87, 91, ..., 'yes', 'no',
        'Software Quality Assurance (QA)  Testing'],
       [73, 77, 74, ..., 'yes', 'no', 'Applications Developer']],
      dtype=object)

In [7]:
data.shape

(20000, 39)

In [8]:
label.shape

(20000,)

In [9]:
list(dataset.columns)

['Acedamic percentage in Operating Systems',
 'percentage in Algorithms',
 'Percentage in Programming Concepts',
 'Percentage in Software Engineering',
 'Percentage in Computer Networks',
 'Percentage in Electronics Subjects',
 'Percentage in Computer Architecture',
 'Percentage in Mathematics',
 'Percentage in Communication skills',
 'Hours working per day',
 'Logical quotient rating',
 'hackathons',
 'coding skills rating',
 'public speaking points',
 'can work long time before system',
 'self-learning capability',
 'Extra-courses did',
 'certifications',
 'workshops',
 'talenttests taken',
 'olympiads',
 'reading and writing skills',
 'memory capability score',
 'Interested subjects',
 'interested career area ',
 'JobHigher Studies',
 'Type of company want to settle in',
 'Taken inputs from seniors or elders',
 'interested in games',
 'Interested Type of Books',
 'Salary Range Expected',
 'In a Realtionship',
 'Gentle or Tuff behaviour',
 'Management or Technical',
 'Salarywork',
 '

In [10]:
data.size

780000

In [11]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [12]:
labelencoder = LabelEncoder()

In [13]:
for i in range(14,38):
    data[:,i] = labelencoder.fit_transform(data[:,i])

In [14]:
data


array([[69, 63, 78, ..., 1, 0, 'Database Developer'],
       [78, 62, 73, ..., 0, 1, 'Portal Administrator'],
       [71, 86, 91, ..., 0, 1, 'Portal Administrator'],
       ...,
       [83, 70, 80, ..., 0, 1, 'Business Intelligence Analyst'],
       [68, 87, 91, ..., 1, 0,
        'Software Quality Assurance (QA)  Testing'],
       [73, 77, 74, ..., 1, 0, 'Applications Developer']], dtype=object)

In [15]:
data.shape

(20000, 39)

# Subsets of Data

## Academic data

In [16]:
academic_data_r=dataset.iloc[:,0:9]

In [17]:
academic_data_r.head()

Acedamic percentage in Operating Systems  percentage in Algorithms  \
0                                        69                        63   
1                                        78                        62   
2                                        71                        86   
3                                        76                        87   
4                                        92                        62   

   Percentage in Programming Concepts  Percentage in Software Engineering  \
0                                  78                                  87   
1                                  73                                  60   
2                                  91                                  87   
3                                  60                                  84   
4                                  90                                  67   

   Percentage in Computer Networks  Percentage in Electronics Subjects  \
0                               94                                  94   
1                               71                                  70   
2                               61                                  81   
3                               89                                  73   
4                               71                                  89   

   Percentage in Computer Architecture  Percentage in Mathematics  \
0                                   87                         84   
1                                   73                         84   
2                                   72                         72   
3                                   62                         88   
4                                   73                         71   

   Percentage in Communication skills  
0                                  61  
1                                  91  
2                                  94  
3                                  69  
4                                  73

In [18]:
academic_data=data[:,0:9]

In [19]:
academic_data

array([[69, 63, 78, ..., 87, 84, 61],
       [78, 62, 73, ..., 73, 84, 91],
       [71, 86, 91, ..., 72, 72, 94],
       ...,
       [83, 70, 80, ..., 69, 94, 88],
       [68, 87, 91, ..., 61, 87, 61],
       [73, 77, 74, ..., 92, 73, 90]], dtype=object)

In [20]:
academic_data.shape

(20000, 9)

In [21]:
np.sum(academic_data)

13858814

In [22]:
 academic_percentage=np.sum(academic_data, axis = 1, keepdims = True)

In [23]:
academic_percentage

array([[717],
       [662],
       [715],
       ...,
       [720],
       [683],
       [698]], dtype=object)

In [140]:
academic_percentage=np.true_divide(academic_percentage, 9)

In [141]:
academic_percentage

array([[79.66666666666667],
       [73.55555555555556],
       [79.44444444444444],
       ...,
       [80.0],
       [75.88888888888889],
       [77.55555555555556]], dtype=object)

## Communication Skills Data

In [26]:
communication_skill_data_r=dataset.iloc[:,[13,21]]

In [27]:
communication_skill_data=data[:,[13,21]]

In [28]:
communication_skill_data_r.head(n=10)

public speaking points reading and writing skills
0                       8                  excellent
1                       3                       poor
2                       3                       poor
3                       5                     medium
4                       3                       poor
5                       1                       poor
6                       3                  excellent
7                       6                       poor
8                       8                       poor
9                       4                  excellent

In [29]:
communication_skill_data

array([[8, 0],
       [3, 2],
       [3, 2],
       ...,
       [3, 1],
       [5, 2],
       [6, 0]], dtype=object)

In [30]:
communication_skill_data.shape

(20000, 2)

In [31]:

np.amax(communication_skill_data, axis=None, out=None)


9

In [32]:
communication_percentage=np.sum(communication_skill_data, axis = 1, keepdims = True)

In [33]:
communication_percentage

array([[8],
       [5],
       [5],
       ...,
       [4],
       [7],
       [6]], dtype=object)

In [34]:
communication_percentage=np.true_divide(communication_percentage,12)

In [35]:
communication_percentage

array([[0.6666666666666666],
       [0.4166666666666667],
       [0.4166666666666667],
       ...,
       [0.3333333333333333],
       [0.5833333333333334],
       [0.5]], dtype=object)

In [144]:
communication_percentage=np.multiply(communication_percentage,100)

In [145]:
communication_percentage

array([[66.66666666666666],
       [41.66666666666667],
       [41.66666666666667],
       ...,
       [33.33333333333333],
       [58.333333333333336],
       [50.0]], dtype=object)

## Teamwork_data

In [38]:
teamwork_data_r=dataset.iloc[:,[27,28,32,33,35,36]]

In [39]:
teamwork_data_r.head()

Taken inputs from seniors or elders interested in games  \
0                                  no                  no   
1                                 yes                 yes   
2                                 yes                 yes   
3                                  no                  no   
4                                  no                 yes   

  Gentle or Tuff behaviour Management or Technical hardsmart worker  \
0                 stubborn              Management      hard worker   
1                   gentle               Technical      hard worker   
2                 stubborn              Management      hard worker   
3                   gentle              Management     smart worker   
4                 stubborn              Management      hard worker   

  worked in teams ever  
0                  yes  
1                   no  
2                   no  
3                  yes  
4                  yes

In [40]:
teamwork_data=data[:,[27,28,32,33,35,36]]

In [41]:
teamwork_data

array([[0, 0, 1, 0, 0, 1],
       [1, 1, 0, 1, 0, 0],
       [1, 1, 1, 0, 0, 0],
       ...,
       [1, 1, 0, 1, 0, 0],
       [1, 0, 0, 0, 1, 1],
       [1, 0, 0, 0, 0, 1]], dtype=object)

In [42]:
teamwork_data.shape

(20000, 6)

In [43]:
teamwork_percentage=np.sum(teamwork_data, axis = 1, keepdims = True)

In [44]:
teamwork_percentage=np.true_divide(teamwork_percentage,6)

In [45]:
teamwork_percentage=np.multiply(teamwork_percentage,100)

In [46]:
teamwork_percentage

array([[33.33333333333333],
       [50.0],
       [50.0],
       ...,
       [50.0],
       [50.0],
       [33.33333333333333]], dtype=object)

# problem_solving_data

In [47]:
problem_solving_data_r=dataset.iloc[:,[10,11,12,19,22,20]]

In [48]:
problem_solving_data_r.head(n=10)

Logical quotient rating  hackathons  coding skills rating  \
0                        4           0                     4   
1                        7           1                     2   
2                        1           4                     1   
3                        1           1                     2   
4                        5           4                     6   
5                        5           3                     8   
6                        3           2                     3   
7                        2           1                     6   
8                        5           2                     4   
9                        9           0                     5   

  talenttests taken memory capability score olympiads  
0                no               excellent       yes  
1                no                  medium        no  
2                no               excellent       yes  
3               yes               excellent        no  
4                no               excellent        no  
5                no                  medium        no  
6                no                    poor        no  
7                no               excellent       yes  
8               yes                    poor        no  
9               yes                    poor       yes

In [49]:
problem_solving_data=data[:,[10,11,12,19,22,20]]

In [50]:
problem_solving_data

array([[4, 0, 4, 0, 0, 1],
       [7, 1, 2, 0, 1, 0],
       [1, 4, 1, 0, 0, 1],
       ...,
       [3, 6, 2, 1, 0, 1],
       [1, 4, 9, 0, 2, 1],
       [3, 1, 7, 0, 0, 1]], dtype=object)

In [51]:
problem_solving_data.shape

(20000, 6)

In [52]:
problem_solving_percentage=np.sum(problem_solving_data,axis=1,keepdims=True)

In [53]:
problem_solving_percentage

array([[9],
       [11],
       [7],
       ...,
       [13],
       [17],
       [12]], dtype=object)

In [77]:
np.amax(problem_solving_data[:,2])

9

In [78]:
problem_solving_percentage=np.true_divide(problem_solving_percentage,37)

In [79]:
problem_solving_percentage=np.multiply(problem_solving_percentage,100)

In [80]:
problem_solving_percentage

array([[24.324324324324326],
       [29.72972972972973],
       [18.91891891891892],
       ...,
       [35.13513513513514],
       [45.94594594594595],
       [32.432432432432435]], dtype=object)

# self_managment_data

In [54]:
self_managment_data_r=dataset.iloc[:,[14,15,29,31,33,34,37]]

In [55]:
self_managment_data_r.head()

can work long time before system self-learning capability  \
0                              yes                      yes   
1                              yes                       no   
2                              yes                       no   
3                               no                      yes   
4                               no                       no   

  Interested Type of Books In a Realtionship Management or Technical  \
0             Prayer books                no              Management   
1                Childrens               yes               Technical   
2                   Travel                no              Management   
3                  Romance               yes              Management   
4                Cookbooks                no              Management   

  Salarywork Introvert  
0     salary        no  
1     salary       yes  
2       work       yes  
3       work       yes  
4       work       yes

In [56]:
self_managment_data=data[:,[14,15,29,31,33,34,37]]

In [57]:
self_managment_data

array([[1, 1, 21, ..., 0, 0, 0],
       [1, 0, 5, ..., 1, 0, 1],
       [1, 0, 29, ..., 0, 1, 1],
       ...,
       [1, 1, 10, ..., 1, 1, 1],
       [0, 0, 29, ..., 0, 1, 0],
       [1, 1, 6, ..., 0, 1, 0]], dtype=object)

In [58]:
self_managment_data.shape

(20000, 7)

In [81]:
np.amax(self_managment_data[:,2])

30

In [82]:
np.amax(self_managment_data[:,4])

1

In [83]:
np.amax(self_managment_data[:,5])

1

In [106]:
self_managment_percentage=np.sum(self_managment_data,axis=1,keepdims=True)

In [107]:
self_managment_percentage

array([[23],
       [9],
       [32],
       ...,
       [16],
       [30],
       [9]], dtype=object)

In [108]:
self_managment_percentage=np.true_divide(self_managment_percentage,36)

In [109]:
self_managment_percentage

array([[0.6388888888888888],
       [0.25],
       [0.8888888888888888],
       ...,
       [0.4444444444444444],
       [0.8333333333333334],
       [0.25]], dtype=object)

In [110]:
self_managment_percentage=np.multiply(self_managment_percentage,100)

In [111]:
self_managment_percentage

array([[63.888888888888886],
       [25.0],
       [88.88888888888889],
       ...,
       [44.44444444444444],
       [83.33333333333334],
       [25.0]], dtype=object)

## Knowledge_data

In [59]:
knowledge_data_r=dataset.iloc[:,[16,17,18,23]]

In [60]:
knowledge_data_r.head()

Extra-courses did     certifications          workshops  \
0               yes  shell programming    cloud computing   
1               yes   machine learning  database security   
2               yes    app development   web technologies   
3                no             python       data science   
4                no    app development    cloud computing   

     Interested subjects  
0        cloud computing  
1               networks  
2                hacking  
3               networks  
4  Computer Architecture

In [61]:
knowledge_data=data[:,[16,17,18,23]]

In [62]:
knowledge_data

array([[1, 8, 0, 4],
       [1, 5, 2, 7],
       [1, 0, 7, 6],
       ...,
       [1, 4, 2, 7],
       [0, 2, 0, 1],
       [1, 0, 2, 1]], dtype=object)

In [63]:
knowledge_data.shape

(20000, 4)

In [113]:
np.amax(knowledge_data[:,1])

8

In [114]:
np.amax(knowledge_data[:,2])

7

In [116]:
np.amax(knowledge_data[:,3])

9

In [118]:
knowledge_percentage=np.sum(knowledge_data,axis=1,keepdims=True)

In [119]:
knowledge_percentage

array([[13],
       [15],
       [14],
       ...,
       [14],
       [3],
       [4]], dtype=object)

In [120]:
knowledge_percentage=np.true_divide(knowledge_percentage,26)

In [122]:
knowledge_percentage=np.multiply(knowledge_percentage,100)

In [123]:
knowledge_percentage

array([[50.0],
       [57.692307692307686],
       [53.84615384615385],
       ...,
       [53.84615384615385],
       [11.538461538461538],
       [15.384615384615385]], dtype=object)

## Interests_data

In [64]:
interests_data_r=dataset.iloc[:,[24,25,26,29,30]]

In [65]:
interests_data_r.head()

interested career area  JobHigher Studies  \
0          system developer     higherstudies   
1  Business process analyst               job   
2                 developer     higherstudies   
3                   testing     higherstudies   
4                   testing     higherstudies   

   Type of company want to settle in Interested Type of Books  \
0                       Web Services             Prayer books   
1                      SAaS services                Childrens   
2                Sales and Marketing                   Travel   
3  Testing and Maintainance Services                  Romance   
4                product development                Cookbooks   

  Salary Range Expected  
0                salary  
1                salary  
2                  Work  
3                  Work  
4                salary

In [66]:
interests_data=data[:,[24,25,26,29,30]]

In [67]:
interests_data

array([[4, 0, 8, 21, 1],
       [0, 1, 4, 5, 1],
       [2, 0, 5, 29, 0],
       ...,
       [1, 0, 4, 10, 0],
       [5, 1, 1, 29, 0],
       [5, 1, 2, 6, 0]], dtype=object)

In [68]:
interests_data.shape

(20000, 5)

In [124]:
np.amax(interests_data[:,0])

5

In [125]:
np.amax(interests_data[:,1])

1

In [126]:
np.amax(interests_data[:,2])

9

In [127]:
np.amax(interests_data[:,3])

30

In [128]:
np.amax(interests_data[:,4])

1

In [131]:
interests_percentage=np.sum(interests_data,axis=1, keepdims= True)

In [132]:
interests_percentage

array([[34],
       [11],
       [36],
       ...,
       [15],
       [36],
       [14]], dtype=object)

In [133]:
interests_percentage=np.true_divide(interests_percentage,48)

In [135]:
interests_percentage=np.multiply(interests_percentage,100)

In [136]:
interests_percentage

array([[70.83333333333334],
       [22.916666666666664],
       [75.0],
       ...,
       [31.25],
       [75.0],
       [29.166666666666668]], dtype=object)

## Concatenate arrays

In [157]:
combine_data=np.concatenate((academic_data,academic_percentage,communication_percentage,teamwork_percentage,problem_solving_percentage,self_managment_percentage,knowledge_percentage,interests_percentage),axis=1)

In [160]:
combine_data.shape

(20000, 16)

In [163]:
X1 = pd.DataFrame(combine_data,columns=['Acedamic percentage in Operating Systems', 
                                        'percentage in Algorithms',
                                        'Percentage in Programming Concepts',
                                        'Percentage in Software Engineering', 
                                        'Percentage in Computer Networks',
                                        'Percentage in Electronics Subjects',
                                        'Percentage in Computer Architecture',
                                        'Percentage in Mathematics',
                                        'Percentage in Communication skills',
                                        'academic_percentage',
                                        'communication_percentage',
                                        'teamwork_percentage',
                                        'problem_solving_percentage',
                                        'self_managment_percentage',
                                        'knowledge_percentage',
                                        'interests_percentage'])

In [164]:
X1.head()

Acedamic percentage in Operating Systems percentage in Algorithms  \
0                                       69                       63   
1                                       78                       62   
2                                       71                       86   
3                                       76                       87   
4                                       92                       62   

  Percentage in Programming Concepts Percentage in Software Engineering  \
0                                 78                                 87   
1                                 73                                 60   
2                                 91                                 87   
3                                 60                                 84   
4                                 90                                 67   

  Percentage in Computer Networks Percentage in Electronics Subjects  \
0                              94                                 94   
1                              71                                 70   
2                              61                                 81   
3                              89                                 73   
4                              71                                 89   

  Percentage in Computer Architecture Percentage in Mathematics  \
0                                  87                        84   
1                                  73                        84   
2                                  72                        72   
3                                  62                        88   
4                                  73                        71   

  Percentage in Communication skills academic_percentage  \
0                                 61             79.6667   
1                                 91             73.5556   
2                                 94             79.4444   
3                                 69             76.4444   
4                                 73             76.4444   

  communication_percentage teamwork_percentage problem_solving_percentage  \
0                  66.6667             33.3333                    24.3243   
1                  41.6667                  50                    29.7297   
2                  41.6667                  50                    18.9189   
3                       50             33.3333                    13.5135   
4                  41.6667                  50                    40.5405   

  self_managment_percentage knowledge_percentage interests_percentage  
0                   63.8889                   50              70.8333  
1                        25              57.6923              22.9167  
2                   88.8889              53.8462                   75  
3                        75              53.8462              72.9167  
4                        25                    0              45.8333

In [297]:
label = labelencoder.fit_transform(label)

In [298]:
label

array([ 7, 18, 18, ...,  1, 24,  0], dtype=int64)

In [287]:
y=pd.DataFrame(label,columns=["Suggested Job Role"])

In [288]:
final_df = pd.concat((X1,y),axis=1)

In [289]:
final_df.head()

Acedamic percentage in Operating Systems percentage in Algorithms  \
0                                       69                       63   
1                                       78                       62   
2                                       71                       86   
3                                       76                       87   
4                                       92                       62   

  Percentage in Programming Concepts Percentage in Software Engineering  \
0                                 78                                 87   
1                                 73                                 60   
2                                 91                                 87   
3                                 60                                 84   
4                                 90                                 67   

  Percentage in Computer Networks Percentage in Electronics Subjects  \
0                              94                                 94   
1                              71                                 70   
2                              61                                 81   
3                              89                                 73   
4                              71                                 89   

  Percentage in Computer Architecture Percentage in Mathematics  \
0                                  87                        84   
1                                  73                        84   
2                                  72                        72   
3                                  62                        88   
4                                  73                        71   

  Percentage in Communication skills academic_percentage  \
0                                 61             79.6667   
1                                 91             73.5556   
2                                 94             79.4444   
3                                 69             76.4444   
4                                 73             76.4444   

  communication_percentage teamwork_percentage problem_solving_percentage  \
0                  66.6667             33.3333                    24.3243   
1                  41.6667                  50                    29.7297   
2                  41.6667                  50                    18.9189   
3                       50             33.3333                    13.5135   
4                  41.6667                  50                    40.5405   

  self_managment_percentage knowledge_percentage interests_percentage  \
0                   63.8889                   50              70.8333   
1                        25              57.6923              22.9167   
2                   88.8889              53.8462                   75   
3                        75              53.8462              72.9167   
4                        25                    0              45.8333   

   Suggested Job Role  
0                   7  
1                  18  
2                  18  
3                  28  
4                   2

In [224]:
X.shape

(20000, 16)

In [225]:
X

array([[69, 63, 78, ..., 63.888888888888886, 50.0, 70.83333333333334],
       [78, 62, 73, ..., 25.0, 57.692307692307686, 22.916666666666664],
       [71, 86, 91, ..., 88.88888888888889, 53.84615384615385, 75.0],
       ...,
       [83, 70, 80, ..., 44.44444444444444, 53.84615384615385, 31.25],
       [68, 87, 91, ..., 83.33333333333334, 11.538461538461538, 75.0],
       [73, 77, 74, ..., 25.0, 15.384615384615385, 29.166666666666668]],
      dtype=object)

In [226]:
Y=label

In [227]:
Y.shape

(20000,)

In [228]:
Y

array([ 7, 18, 18, ...,  1, 24,  0])

In [229]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [230]:
test = SelectKBest(score_func=chi2, k=16)
fit = test.fit(X, Y)

In [231]:
np.set_printoptions(suppress=True)
print(fit.scores_)

[ 18.38034544  26.26991883  51.5398971   59.78959158  38.37664406
  56.65610078  23.31612484  31.38669513  31.52321969   3.66516634
 447.14703593 417.61605401 159.43569869 393.02932584 151.63485915
 252.38229034]


In [232]:
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn import preprocessing 
from sklearn.metrics import accuracy_score

In [242]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=10)

In [243]:
clf = tree.DecisionTreeClassifier()

In [244]:
clf = clf.fit(X_train, y_train)

In [245]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [246]:
y_pred = clf.predict(X_test)

In [247]:
y_pred

array([31, 17, 15, ..., 23,  2, 21], dtype=int64)

In [254]:
cm = confusion_matrix(y_test,y_pred)
accuracy = accuracy_score(y_test,y_pred)

In [257]:
print("confusion matrics=",cm)
print("  ")
print("accuracy=",accuracy*100)

confusion matrics= [[4 4 6 ... 2 1 5]
 [4 1 4 ... 2 2 5]
 [3 3 4 ... 4 1 3]
 ...
 [5 2 5 ... 2 4 3]
 [4 1 2 ... 4 4 4]
 [3 4 2 ... 1 5 2]]
  
accuracy= 3.6249999999999996


In [253]:
final_df.head()

Acedamic percentage in Operating Systems percentage in Algorithms  \
0                                       69                       63   
1                                       78                       62   
2                                       71                       86   
3                                       76                       87   
4                                       92                       62   

  Percentage in Programming Concepts Percentage in Software Engineering  \
0                                 78                                 87   
1                                 73                                 60   
2                                 91                                 87   
3                                 60                                 84   
4                                 90                                 67   

  Percentage in Computer Networks Percentage in Electronics Subjects  \
0                              94                                 94   
1                              71                                 70   
2                              61                                 81   
3                              89                                 73   
4                              71                                 89   

  Percentage in Computer Architecture Percentage in Mathematics  \
0                                  87                        84   
1                                  73                        84   
2                                  72                        72   
3                                  62                        88   
4                                  73                        71   

  Percentage in Communication skills academic_percentage  \
0                                 61             79.6667   
1                                 91             73.5556   
2                                 94             79.4444   
3                                 69             76.4444   
4                                 73             76.4444   

  communication_percentage teamwork_percentage problem_solving_percentage  \
0                  66.6667             33.3333                    24.3243   
1                  41.6667                  50                    29.7297   
2                  41.6667                  50                    18.9189   
3                       50             33.3333                    13.5135   
4                  41.6667                  50                    40.5405   

  self_managment_percentage knowledge_percentage interests_percentage  \
0                   63.8889                   50              70.8333   
1                        25              57.6923              22.9167   
2                   88.8889              53.8462                   75   
3                        75              53.8462              72.9167   
4                        25                    0              45.8333   

   Suggested Job Role  
0                   7  
1                  18  
2                  18  
3                  28  
4                   2

In [276]:
test=X[0,:]

In [277]:
test

array([69, 63, 78, 87, 94, 94, 87, 84, 61, 79.66666666666667,
       66.66666666666666, 33.33333333333333, 24.324324324324326,
       63.888888888888886, 50.0, 70.83333333333334], dtype=object)

In [278]:
X_test.dtype

dtype('O')

In [282]:
test=test.reshape(1, -1)

In [284]:
pred = clf.predict(test)


In [285]:
pred

array([7], dtype=int64)