In [2]:
import pandas as pd
import numpy as np
from sklearn import decomposition
import matplotlib.pyplot as plt

In [3]:
dataset = pd.read_csv("row_data.csv")

In [4]:
dataset


Acedamic percentage in Operating Systems  percentage in Algorithms  \
0                                            69                        63   
1                                            78                        62   
2                                            71                        86   
3                                            76                        87   
4                                            92                        62   
5                                            88                        86   
6                                            93                        77   
7                                            84                        72   
8                                            73                        66   
9                                            62                        76   
10                                           73                        80   
11                                           63                        76   
12                                           63                        64   
13                                           68                        93   
14                                           90                        83   
15                                           94                        71   
16                                           60                        92   
17                                           92                        86   
18                                           82                        91   
19                                           90                        73   
20                                           67                        61   
21                                           65                        61   
22                                           84                        62   
23                                           74                        89   
24                                           92                        67   
25                                           75                        74   
26                                           90                        82   
27                                           71                        60   
28                                           83                        82   
29                                           83                        68   
...                                         ...                       ...   
19970                                        65                        84   
19971                                        88                        92   
19972                                        64                        74   
19973                                        64                        66   
19974                                        68                        61   
19975                                        84                        68   
19976                                        67                        69   
19977                                        88                        71   
19978                                        71                        73   
19979                                        60                        77   
19980                                        78                        64   
19981                                        80                        89   
19982                                        64                        94   
19983                                        80                        92   
19984                                        72                        69   
19985                                        65                        77   
19986                                        74                        72   
19987                                        82                        62   
19988                                        64                        85   
19989                                        73                        60   
199

# Exploratory Data Analysis

In [651]:
dataset.describe() 


Acedamic percentage in Operating Systems  percentage in Algorithms  \
count                              20000.000000              20000.000000   
mean                                  77.002300                 76.948200   
std                                   10.085697                 10.101733   
min                                   60.000000                 60.000000   
25%                                   68.000000                 68.000000   
50%                                   77.000000                 77.000000   
75%                                   86.000000                 86.000000   
max                                   94.000000                 94.000000   

       Percentage in Programming Concepts  Percentage in Software Engineering  \
count                        20000.000000                        20000.000000   
mean                            77.017550                           77.094500   
std                             10.134815                           10.087837   
min                             60.000000                           60.000000   
25%                             68.000000                           68.000000   
50%                             77.000000                           77.000000   
75%                             86.000000                           86.000000   
max                             94.000000                           94.000000   

       Percentage in Computer Networks  Percentage in Electronics Subjects  \
count                     20000.000000                        20000.000000   
mean                         76.958200                           77.015550   
std                          10.020088                           10.168888   
min                          60.000000                           60.000000   
25%                          68.000000                           68.000000   
50%                          77.000000                           77.000000   
75%                          85.000000                           86.000000   
max                          94.000000                           94.000000   

       Percentage in Computer Architecture  Percentage in Mathematics  \
count                         20000.000000               20000.000000   
mean                             77.069850                  76.913100   
std                              10.069059                  10.138555   
min                              60.000000                  60.000000   
25%                              68.000000                  68.000000   
50%                              77.000000                  77.000000   
75%                              86.000000                  86.000000   
max                              94.000000                  94.000000   

       Percentage in Communication skills  Hours working per day  \
count                        20000.000000           20000.000000   
mean                            76.921450               7.985950   
std                             10.103494               2.593798   
min                             60.000000               4.000000   
25%                             68.000000               6.000000   
50%                             77.000000               8.000000   
75%                             86.000000              10.000000   
max                             94.000000              12.000000   

       Logical quotient rating    hackathons  coding skills rating  \
count             20000.000000  20000.000000          20000.000000   
mean                  4.995050      2.992650              5.004750   
std                   2.578383      2.005791              2.576831   
min                   1.000000      0.000000              1.000000   
25%                   3.000000      1.000000              3.000000   
50%                   5.000000      3.000000              5.000000   
75%                   7.000000      5.000000              7.000000   
max                   9.000000      6.000000     

In [652]:
data = dataset.iloc[:,:].values
label = dataset.iloc[:,-1].values

In [653]:
data

array([[69, 63, 78, ..., 'yes', 'no', 'Database Developer'],
       [78, 62, 73, ..., 'no', 'yes', 'Portal Administrator'],
       [71, 86, 91, ..., 'no', 'yes', 'Portal Administrator'],
       ...,
       [83, 70, 80, ..., 'no', 'yes', 'Business Intelligence Analyst'],
       [68, 87, 91, ..., 'yes', 'no',
        'Software Quality Assurance (QA)  Testing'],
       [73, 77, 74, ..., 'yes', 'no', 'Applications Developer']],
      dtype=object)

In [654]:
data.shape

(20000, 39)

In [655]:
label.shape

(20000,)

In [656]:
list(dataset.columns)

['Acedamic percentage in Operating Systems',
 'percentage in Algorithms',
 'Percentage in Programming Concepts',
 'Percentage in Software Engineering',
 'Percentage in Computer Networks',
 'Percentage in Electronics Subjects',
 'Percentage in Computer Architecture',
 'Percentage in Mathematics',
 'Percentage in Communication skills',
 'Hours working per day',
 'Logical quotient rating',
 'hackathons',
 'coding skills rating',
 'public speaking points',
 'can work long time before system',
 'self-learning capability',
 'Extra-courses did',
 'certifications',
 'workshops',
 'talenttests taken',
 'olympiads',
 'reading and writing skills',
 'memory capability score',
 'Interested subjects',
 'interested career area ',
 'JobHigher Studies',
 'Type of company want to settle in',
 'Taken inputs from seniors or elders',
 'interested in games',
 'Interested Type of Books',
 'Salary Range Expected',
 'In a Realtionship',
 'Gentle or Tuff behaviour',
 'Management or Technical',
 'Salarywork',
 '

In [657]:
data.size

780000

In [658]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [659]:
labelencoder = LabelEncoder()

In [660]:
for i in range(14,38):
    data[:,i] = labelencoder.fit_transform(data[:,i])

In [661]:
data


array([[69, 63, 78, ..., 1, 0, 'Database Developer'],
       [78, 62, 73, ..., 0, 1, 'Portal Administrator'],
       [71, 86, 91, ..., 0, 1, 'Portal Administrator'],
       ...,
       [83, 70, 80, ..., 0, 1, 'Business Intelligence Analyst'],
       [68, 87, 91, ..., 1, 0,
        'Software Quality Assurance (QA)  Testing'],
       [73, 77, 74, ..., 1, 0, 'Applications Developer']], dtype=object)

In [662]:
data.shape

(20000, 39)

# Subsets of Data

## Academic data

In [663]:
academic_data_r=dataset.iloc[:,0:9]

In [664]:
academic_data_r.head()

Acedamic percentage in Operating Systems  percentage in Algorithms  \
0                                        69                        63   
1                                        78                        62   
2                                        71                        86   
3                                        76                        87   
4                                        92                        62   

   Percentage in Programming Concepts  Percentage in Software Engineering  \
0                                  78                                  87   
1                                  73                                  60   
2                                  91                                  87   
3                                  60                                  84   
4                                  90                                  67   

   Percentage in Computer Networks  Percentage in Electronics Subjects  \
0                               94                                  94   
1                               71                                  70   
2                               61                                  81   
3                               89                                  73   
4                               71                                  89   

   Percentage in Computer Architecture  Percentage in Mathematics  \
0                                   87                         84   
1                                   73                         84   
2                                   72                         72   
3                                   62                         88   
4                                   73                         71   

   Percentage in Communication skills  
0                                  61  
1                                  91  
2                                  94  
3                                  69  
4                                  73

In [665]:
academic_data=data[:,0:9]

In [666]:
academic_data

array([[69, 63, 78, ..., 87, 84, 61],
       [78, 62, 73, ..., 73, 84, 91],
       [71, 86, 91, ..., 72, 72, 94],
       ...,
       [83, 70, 80, ..., 69, 94, 88],
       [68, 87, 91, ..., 61, 87, 61],
       [73, 77, 74, ..., 92, 73, 90]], dtype=object)

In [667]:
academic_data.shape

(20000, 9)

In [668]:
np.sum(academic_data)

13858814

In [669]:
 academic_percentage=np.sum(academic_data, axis = 1, keepdims = True)

In [670]:
academic_percentage

array([[717],
       [662],
       [715],
       ...,
       [720],
       [683],
       [698]], dtype=object)

In [671]:
academic_percentage=np.true_divide(academic_percentage, 9)

In [672]:
academic_percentage

array([[79.66666666666667],
       [73.55555555555556],
       [79.44444444444444],
       ...,
       [80.0],
       [75.88888888888889],
       [77.55555555555556]], dtype=object)

## Communication Skills Data

In [673]:
communication_skill_data_r=dataset.iloc[:,[13,21]]

In [674]:
communication_skill_data=data[:,[13,21]]

In [675]:
communication_skill_data_r.head(n=10)

public speaking points reading and writing skills
0                       8                  excellent
1                       3                       poor
2                       3                       poor
3                       5                     medium
4                       3                       poor
5                       1                       poor
6                       3                  excellent
7                       6                       poor
8                       8                       poor
9                       4                  excellent

In [676]:
communication_skill_data

array([[8, 0],
       [3, 2],
       [3, 2],
       ...,
       [3, 1],
       [5, 2],
       [6, 0]], dtype=object)

In [677]:
communication_skill_data.shape

(20000, 2)

In [678]:

np.amax(communication_skill_data, axis=None, out=None)


9

In [679]:
communication_percentage=np.sum(communication_skill_data, axis = 1, keepdims = True)

In [680]:
communication_percentage

array([[8],
       [5],
       [5],
       ...,
       [4],
       [7],
       [6]], dtype=object)

In [681]:
communication_percentage=np.true_divide(communication_percentage,12)

In [682]:
communication_percentage

array([[0.6666666666666666],
       [0.4166666666666667],
       [0.4166666666666667],
       ...,
       [0.3333333333333333],
       [0.5833333333333334],
       [0.5]], dtype=object)

In [683]:
communication_percentage=np.multiply(communication_percentage,100)

In [684]:
communication_percentage

array([[66.66666666666666],
       [41.66666666666667],
       [41.66666666666667],
       ...,
       [33.33333333333333],
       [58.333333333333336],
       [50.0]], dtype=object)

## Teamwork_data

In [685]:
teamwork_data_r=dataset.iloc[:,[27,28,32,33,35,36]]

In [686]:
teamwork_data_r.head()

Taken inputs from seniors or elders interested in games  \
0                                  no                  no   
1                                 yes                 yes   
2                                 yes                 yes   
3                                  no                  no   
4                                  no                 yes   

  Gentle or Tuff behaviour Management or Technical hardsmart worker  \
0                 stubborn              Management      hard worker   
1                   gentle               Technical      hard worker   
2                 stubborn              Management      hard worker   
3                   gentle              Management     smart worker   
4                 stubborn              Management      hard worker   

  worked in teams ever  
0                  yes  
1                   no  
2                   no  
3                  yes  
4                  yes

In [687]:
teamwork_data=data[:,[27,28,32,33,35,36]]

In [688]:
teamwork_data

array([[0, 0, 1, 0, 0, 1],
       [1, 1, 0, 1, 0, 0],
       [1, 1, 1, 0, 0, 0],
       ...,
       [1, 1, 0, 1, 0, 0],
       [1, 0, 0, 0, 1, 1],
       [1, 0, 0, 0, 0, 1]], dtype=object)

In [689]:
teamwork_data.shape

(20000, 6)

In [690]:
teamwork_percentage=np.sum(teamwork_data, axis = 1, keepdims = True)

In [691]:
teamwork_percentage=np.true_divide(teamwork_percentage,6)

In [692]:
teamwork_percentage=np.multiply(teamwork_percentage,100)

In [693]:
teamwork_percentage

array([[33.33333333333333],
       [50.0],
       [50.0],
       ...,
       [50.0],
       [50.0],
       [33.33333333333333]], dtype=object)

# problem_solving_data

In [694]:
problem_solving_data_r=dataset.iloc[:,[10,11,12,19,22,20]]

In [695]:
problem_solving_data_r.head(n=10)

Logical quotient rating  hackathons  coding skills rating  \
0                        4           0                     4   
1                        7           1                     2   
2                        1           4                     1   
3                        1           1                     2   
4                        5           4                     6   
5                        5           3                     8   
6                        3           2                     3   
7                        2           1                     6   
8                        5           2                     4   
9                        9           0                     5   

  talenttests taken memory capability score olympiads  
0                no               excellent       yes  
1                no                  medium        no  
2                no               excellent       yes  
3               yes               excellent        no  
4                no               excellent        no  
5                no                  medium        no  
6                no                    poor        no  
7                no               excellent       yes  
8               yes                    poor        no  
9               yes                    poor       yes

In [696]:
problem_solving_data=data[:,[10,11,12,19,22,20]]

In [697]:
problem_solving_data

array([[4, 0, 4, 0, 0, 1],
       [7, 1, 2, 0, 1, 0],
       [1, 4, 1, 0, 0, 1],
       ...,
       [3, 6, 2, 1, 0, 1],
       [1, 4, 9, 0, 2, 1],
       [3, 1, 7, 0, 0, 1]], dtype=object)

In [698]:
problem_solving_data.shape

(20000, 6)

In [699]:
problem_solving_percentage=np.sum(problem_solving_data,axis=1,keepdims=True)

In [700]:
problem_solving_percentage

array([[9],
       [11],
       [7],
       ...,
       [13],
       [17],
       [12]], dtype=object)

In [701]:
np.amax(problem_solving_data[:,2])

9

In [702]:
problem_solving_percentage=np.true_divide(problem_solving_percentage,37)

In [703]:
problem_solving_percentage=np.multiply(problem_solving_percentage,100)

In [704]:
problem_solving_percentage

array([[24.324324324324326],
       [29.72972972972973],
       [18.91891891891892],
       ...,
       [35.13513513513514],
       [45.94594594594595],
       [32.432432432432435]], dtype=object)

# self_managment_data

In [705]:
self_managment_data_r=dataset.iloc[:,[14,15,29,31,33,34,37]]

In [706]:
self_managment_data_r.head()

can work long time before system self-learning capability  \
0                              yes                      yes   
1                              yes                       no   
2                              yes                       no   
3                               no                      yes   
4                               no                       no   

  Interested Type of Books In a Realtionship Management or Technical  \
0             Prayer books                no              Management   
1                Childrens               yes               Technical   
2                   Travel                no              Management   
3                  Romance               yes              Management   
4                Cookbooks                no              Management   

  Salarywork Introvert  
0     salary        no  
1     salary       yes  
2       work       yes  
3       work       yes  
4       work       yes

In [707]:
self_managment_data=data[:,[14,15,29,31,33,34,37]]

In [708]:
self_managment_data

array([[1, 1, 21, ..., 0, 0, 0],
       [1, 0, 5, ..., 1, 0, 1],
       [1, 0, 29, ..., 0, 1, 1],
       ...,
       [1, 1, 10, ..., 1, 1, 1],
       [0, 0, 29, ..., 0, 1, 0],
       [1, 1, 6, ..., 0, 1, 0]], dtype=object)

In [709]:
self_managment_data.shape

(20000, 7)

In [710]:
np.amax(self_managment_data[:,2])

30

In [711]:
np.amax(self_managment_data[:,4])

1

In [712]:
np.amax(self_managment_data[:,5])

1

In [713]:
self_managment_percentage=np.sum(self_managment_data,axis=1,keepdims=True)

In [714]:
self_managment_percentage

array([[23],
       [9],
       [32],
       ...,
       [16],
       [30],
       [9]], dtype=object)

In [715]:
self_managment_percentage=np.true_divide(self_managment_percentage,36)

In [716]:
self_managment_percentage

array([[0.6388888888888888],
       [0.25],
       [0.8888888888888888],
       ...,
       [0.4444444444444444],
       [0.8333333333333334],
       [0.25]], dtype=object)

In [717]:
self_managment_percentage=np.multiply(self_managment_percentage,100)

In [718]:
self_managment_percentage

array([[63.888888888888886],
       [25.0],
       [88.88888888888889],
       ...,
       [44.44444444444444],
       [83.33333333333334],
       [25.0]], dtype=object)

## Knowledge_data

In [719]:
knowledge_data_r=dataset.iloc[:,[16,17,18,23]]

In [720]:
knowledge_data_r.head()

Extra-courses did     certifications          workshops  \
0               yes  shell programming    cloud computing   
1               yes   machine learning  database security   
2               yes    app development   web technologies   
3                no             python       data science   
4                no    app development    cloud computing   

     Interested subjects  
0        cloud computing  
1               networks  
2                hacking  
3               networks  
4  Computer Architecture

In [721]:
knowledge_data=data[:,[16,17,18,23]]

In [722]:
knowledge_data

array([[1, 8, 0, 4],
       [1, 5, 2, 7],
       [1, 0, 7, 6],
       ...,
       [1, 4, 2, 7],
       [0, 2, 0, 1],
       [1, 0, 2, 1]], dtype=object)

In [723]:
knowledge_data.shape

(20000, 4)

In [724]:
np.amax(knowledge_data[:,1])

8

In [725]:
np.amax(knowledge_data[:,2])

7

In [726]:
np.amax(knowledge_data[:,3])

9

In [727]:
knowledge_percentage=np.sum(knowledge_data,axis=1,keepdims=True)

In [728]:
knowledge_percentage

array([[13],
       [15],
       [14],
       ...,
       [14],
       [3],
       [4]], dtype=object)

In [729]:
knowledge_percentage=np.true_divide(knowledge_percentage,26)

In [730]:
knowledge_percentage=np.multiply(knowledge_percentage,100)

In [731]:
knowledge_percentage

array([[50.0],
       [57.692307692307686],
       [53.84615384615385],
       ...,
       [53.84615384615385],
       [11.538461538461538],
       [15.384615384615385]], dtype=object)

## Interests_data

In [732]:
interests_data_r=dataset.iloc[:,[24,25,26,29,30]]

In [733]:
interests_data_r.head()

interested career area  JobHigher Studies  \
0          system developer     higherstudies   
1  Business process analyst               job   
2                 developer     higherstudies   
3                   testing     higherstudies   
4                   testing     higherstudies   

   Type of company want to settle in Interested Type of Books  \
0                       Web Services             Prayer books   
1                      SAaS services                Childrens   
2                Sales and Marketing                   Travel   
3  Testing and Maintainance Services                  Romance   
4                product development                Cookbooks   

  Salary Range Expected  
0                salary  
1                salary  
2                  Work  
3                  Work  
4                salary

In [734]:
interests_data=data[:,[24,25,26,29,30]]

In [735]:
interests_data

array([[4, 0, 8, 21, 1],
       [0, 1, 4, 5, 1],
       [2, 0, 5, 29, 0],
       ...,
       [1, 0, 4, 10, 0],
       [5, 1, 1, 29, 0],
       [5, 1, 2, 6, 0]], dtype=object)

In [736]:
interests_data.shape

(20000, 5)

In [737]:
np.amax(interests_data[:,0])

5

In [738]:
np.amax(interests_data[:,1])

1

In [739]:
np.amax(interests_data[:,2])

9

In [740]:
np.amax(interests_data[:,3])

30

In [741]:
np.amax(interests_data[:,4])

1

In [742]:
interests_percentage=np.sum(interests_data,axis=1, keepdims= True)

In [743]:
interests_percentage

array([[34],
       [11],
       [36],
       ...,
       [15],
       [36],
       [14]], dtype=object)

In [744]:
interests_percentage=np.true_divide(interests_percentage,48)

In [745]:
interests_percentage=np.multiply(interests_percentage,100)

In [746]:
interests_percentage

array([[70.83333333333334],
       [22.916666666666664],
       [75.0],
       ...,
       [31.25],
       [75.0],
       [29.166666666666668]], dtype=object)

## Concatenate arrays

In [747]:
combine_data=np.concatenate((academic_data,academic_percentage,communication_percentage,teamwork_percentage,problem_solving_percentage,self_managment_percentage,knowledge_percentage,interests_percentage),axis=1)

In [748]:
combine_data.shape

(20000, 16)

In [749]:
X1 = pd.DataFrame(combine_data,columns=['Acedamic percentage in Operating Systems', 
                                        'percentage in Algorithms',
                                        'Percentage in Programming Concepts',
                                        'Percentage in Software Engineering', 
                                        'Percentage in Computer Networks',
                                        'Percentage in Electronics Subjects',
                                        'Percentage in Computer Architecture',
                                        'Percentage in Mathematics',
                                        'Percentage in Communication skills',
                                        'academic_percentage',
                                        'communication_percentage',
                                        'teamwork_percentage',
                                        'problem_solving_percentage',
                                        'self_managment_percentage',
                                        'knowledge_percentage',
                                        'interests_percentage'])

In [750]:
X1.head()

Acedamic percentage in Operating Systems percentage in Algorithms  \
0                                       69                       63   
1                                       78                       62   
2                                       71                       86   
3                                       76                       87   
4                                       92                       62   

  Percentage in Programming Concepts Percentage in Software Engineering  \
0                                 78                                 87   
1                                 73                                 60   
2                                 91                                 87   
3                                 60                                 84   
4                                 90                                 67   

  Percentage in Computer Networks Percentage in Electronics Subjects  \
0                              94                                 94   
1                              71                                 70   
2                              61                                 81   
3                              89                                 73   
4                              71                                 89   

  Percentage in Computer Architecture Percentage in Mathematics  \
0                                  87                        84   
1                                  73                        84   
2                                  72                        72   
3                                  62                        88   
4                                  73                        71   

  Percentage in Communication skills academic_percentage  \
0                                 61             79.6667   
1                                 91             73.5556   
2                                 94             79.4444   
3                                 69             76.4444   
4                                 73             76.4444   

  communication_percentage teamwork_percentage problem_solving_percentage  \
0                  66.6667             33.3333                    24.3243   
1                  41.6667                  50                    29.7297   
2                  41.6667                  50                    18.9189   
3                       50             33.3333                    13.5135   
4                  41.6667                  50                    40.5405   

  self_managment_percentage knowledge_percentage interests_percentage  
0                   63.8889                   50              70.8333  
1                        25              57.6923              22.9167  
2                   88.8889              53.8462                   75  
3                        75              53.8462              72.9167  
4                        25                    0              45.8333

In [751]:
label

array(['Database Developer', 'Portal Administrator',
       'Portal Administrator', ..., 'Business Intelligence Analyst',
       'Software Quality Assurance (QA)  Testing',
       'Applications Developer'], dtype=object)

In [752]:
label = labelencoder.fit_transform(label)

In [753]:
label

array([ 7, 18, 18, ...,  1, 24,  0])

In [754]:
y=pd.DataFrame(label,columns=["Suggested Job Role"])

In [755]:
final_df = pd.concat((X1,y),axis=1)

In [756]:
final_df.head()

Acedamic percentage in Operating Systems percentage in Algorithms  \
0                                       69                       63   
1                                       78                       62   
2                                       71                       86   
3                                       76                       87   
4                                       92                       62   

  Percentage in Programming Concepts Percentage in Software Engineering  \
0                                 78                                 87   
1                                 73                                 60   
2                                 91                                 87   
3                                 60                                 84   
4                                 90                                 67   

  Percentage in Computer Networks Percentage in Electronics Subjects  \
0                              94                                 94   
1                              71                                 70   
2                              61                                 81   
3                              89                                 73   
4                              71                                 89   

  Percentage in Computer Architecture Percentage in Mathematics  \
0                                  87                        84   
1                                  73                        84   
2                                  72                        72   
3                                  62                        88   
4                                  73                        71   

  Percentage in Communication skills academic_percentage  \
0                                 61             79.6667   
1                                 91             73.5556   
2                                 94             79.4444   
3                                 69             76.4444   
4                                 73             76.4444   

  communication_percentage teamwork_percentage problem_solving_percentage  \
0                  66.6667             33.3333                    24.3243   
1                  41.6667                  50                    29.7297   
2                  41.6667                  50                    18.9189   
3                       50             33.3333                    13.5135   
4                  41.6667                  50                    40.5405   

  self_managment_percentage knowledge_percentage interests_percentage  \
0                   63.8889                   50              70.8333   
1                        25              57.6923              22.9167   
2                   88.8889              53.8462                   75   
3                        75              53.8462              72.9167   
4                        25                    0              45.8333   

   Suggested Job Role  
0                   7  
1                  18  
2                  18  
3                  28  
4                   2

In [757]:
X.shape

(20000, 16)

In [758]:
X

array([[69, 63, 78, ..., 63.888888888888886, 50.0, 70.83333333333334],
       [78, 62, 73, ..., 25.0, 57.692307692307686, 22.916666666666664],
       [71, 86, 91, ..., 88.88888888888889, 53.84615384615385, 75.0],
       ...,
       [83, 70, 80, ..., 44.44444444444444, 53.84615384615385, 31.25],
       [68, 87, 91, ..., 83.33333333333334, 11.538461538461538, 75.0],
       [73, 77, 74, ..., 25.0, 15.384615384615385, 29.166666666666668]],
      dtype=object)

In [759]:
Y=label

In [760]:
Y.shape

(20000,)

In [761]:
Y

array([ 7, 18, 18, ...,  1, 24,  0])

In [762]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [763]:
test = SelectKBest(score_func=chi2, k=16)
fit = test.fit(X, Y)

In [764]:
np.set_printoptions(suppress=True)
print(fit.scores_)

[ 18.38034544  26.26991883  51.5398971   59.78959158  38.37664406
  56.65610078  23.31612484  31.38669513  31.52321969   3.66516634
 447.14703593 417.61605401 159.43569869 393.02932584 151.63485915
 252.38229034]


In [765]:
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn import preprocessing 
from sklearn.metrics import accuracy_score

In [766]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=10)

In [767]:
clf = tree.DecisionTreeClassifier()

In [768]:
clf = clf.fit(X_train, y_train)

In [769]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [770]:
y_pred = clf.predict(X_test)

In [771]:
y_pred

array([31, 17, 15, ..., 23,  2, 21])

In [772]:
cm = confusion_matrix(y_test,y_pred)
accuracy = accuracy_score(y_test,y_pred)

In [773]:
print("confusion matrics=",cm)
print("  ")
print("accuracy=",accuracy*100)

confusion matrics= [[4 5 3 ... 5 2 5]
 [2 1 3 ... 3 1 6]
 [3 1 5 ... 5 1 6]
 ...
 [3 5 2 ... 2 2 1]
 [4 3 1 ... 4 4 2]
 [5 4 2 ... 4 2 3]]
  
accuracy= 3.2


In [797]:
final_df.head(n=10)

Acedamic percentage in Operating Systems percentage in Algorithms  \
0                                       69                       63   
1                                       78                       62   
2                                       71                       86   
3                                       76                       87   
4                                       92                       62   
5                                       88                       86   
6                                       93                       77   
7                                       84                       72   
8                                       73                       66   
9                                       62                       76   

  Percentage in Programming Concepts Percentage in Software Engineering  \
0                                 78                                 87   
1                                 73                                 60   
2                                 91                                 87   
3                                 60                                 84   
4                                 90                                 67   
5                                 62                                 79   
6                                 69                                 79   
7                                 88                                 62   
8                                 66                                 81   
9                                 85                                 91   

  Percentage in Computer Networks Percentage in Electronics Subjects  \
0                              94                                 94   
1                              71                                 70   
2                              61                                 81   
3                              89                                 73   
4                              71                                 89   
5                              93                                 84   
6                              90                                 93   
7                              66                                 63   
8                              81                                 69   
9                              82                                 69   

  Percentage in Computer Architecture Percentage in Mathematics  \
0                                  87                        84   
1                                  73                        84   
2                                  72                        72   
3                                  62                        88   
4                                  73                        71   
5                                  69                        71   
6                                  73                        63   
7                                  78                        94   
8                                  61                        87   
9                                  63                        63   

  Percentage in Communication skills academic_percentage  \
0                                 61             79.6667   
1                                 91             73.5556   
2                                 94             79.4444   
3                                 69             76.4444   
4                                 73             76.4444   
5                                 82             79.3333   
6                                 77             79.3333   
7                                 60             74.1111   
8                                 90             74.8889   
9                                 81             74.6667   

  communication_percentage teamwork_percentage problem_solving_percentage  \
0                  66.6667             33.3333                    24.3243   
1                  41.6667                  50  

In [775]:
test=X[0,:]

In [776]:
test

array([69, 63, 78, 87, 94, 94, 87, 84, 61, 79.66666666666667,
       66.66666666666666, 33.33333333333333, 24.324324324324326,
       63.888888888888886, 50.0, 70.83333333333334], dtype=object)

In [777]:
X_test.dtype

dtype('O')

In [778]:
test=test.reshape(1, -1)

In [779]:
pred = clf.predict(test)


In [780]:
pred

array([7])

In [781]:
label1 = dataset.iloc[:,-1].values

In [782]:
label1=pd.DataFrame(label1,columns=["Suggested Job Role "])

In [783]:
label2=pd.DataFrame(label,columns=["Suggested Job Role map"])

In [784]:
label_map=pd.concat((label1,label2),axis=1)

In [785]:
label_map.head()

Suggested Job Role   Suggested Job Role map
0              Database Developer                       7
1            Portal Administrator                      18
2            Portal Administrator                      18
3  Systems Security Administrator                      28
4        Business Systems Analyst                       2

In [786]:
label_map=label_map.drop_duplicates()

In [791]:
label_map=label_map.sort_values('Suggested Job Role map')

In [792]:
label_map

Suggested Job Role   Suggested Job Role map
52                     Applications Developer                       0
7               Business Intelligence Analyst                       1
4                    Business Systems Analyst                       2
18                       CRM Business Analyst                       3
9                     CRM Technical Developer                       4
39                             Data Architect                       5
57                     Database Administrator                       6
0                          Database Developer                       7
47                           Database Manager                       8
34                                Design & UX                       9
42                         E-Commerce Analyst                      10
17               Information Security Analyst                      11
45             Information Technology Auditor                      12
28             Information Technology Manager                      13
10              Mobile Applications Developer                      14
58                           Network Engineer                      15
38             Network Security Administrator                      16
79                  Network Security Engineer                      17
1                        Portal Administrator                      18
30                         Programmer Analyst                      19
27                            Project Manager                      20
14                Quality Assurance Associate                      21
41                         Software Developer                      22
70                          Software Engineer                      23
103  Software Quality Assurance (QA)  Testing                      24
5                   Software Systems Engineer                      25
35                        Solutions Architect                      26
37                            Systems Analyst                      27
3              Systems Security Administrator                      28
77                         Technical Engineer                      29
43    Technical ServicesHelp DeskTech Support                      30
23                          Technical Support                      31
11                                UX Designer                      32
15                              Web Developer                      33

In [800]:
test2=X[0:10,:]

In [801]:
test2

array([[69, 63, 78, 87, 94, 94, 87, 84, 61, 79.66666666666667,
        66.66666666666666, 33.33333333333333, 24.324324324324326,
        63.888888888888886, 50.0, 70.83333333333334],
       [78, 62, 73, 60, 71, 70, 73, 84, 91, 73.55555555555556,
        41.66666666666667, 50.0, 29.72972972972973, 25.0,
        57.692307692307686, 22.916666666666664],
       [71, 86, 91, 87, 61, 81, 72, 72, 94, 79.44444444444444,
        41.66666666666667, 50.0, 18.91891891891892, 88.88888888888889,
        53.84615384615385, 75.0],
       [76, 87, 60, 84, 89, 73, 62, 88, 69, 76.44444444444444, 50.0,
        33.33333333333333, 13.513513513513514, 75.0, 53.84615384615385,
        72.91666666666666],
       [92, 62, 90, 67, 71, 89, 73, 71, 73, 76.44444444444444,
        41.66666666666667, 50.0, 40.54054054054054, 25.0, 0.0,
        45.83333333333333],
       [88, 86, 62, 79, 93, 84, 69, 71, 82, 79.33333333333333, 25.0,
        83.33333333333334, 45.94594594594595, 83.33333333333334,
        65.38461538461

In [805]:
test2_test=label[0:10]

In [806]:
test2_test

array([ 7, 18, 18, 28,  2, 25,  7,  1,  2,  4])

In [802]:
pred = clf.predict(test2)

In [803]:
pred

array([ 7, 18, 18, 28,  2, 25,  7, 12,  2,  6])

In [807]:
accuracy = accuracy_score(test2_test,pred)

In [809]:
accuracy*100

80.0

In [811]:
## Testing xgb

In [815]:
y

Suggested Job Role
0                       7
1                      18
2                      18
3                      28
4                       2
5                      25
6                       7
7                       1
8                       2
9                       4
10                     14
11                     32
12                      4
13                      2
14                     21
15                     33
16                     33
17                     11
18                      3
19                     11
20                      7
21                      2
22                     21
23                     31
24                     31
25                     11
26                      1
27                     20
28                     13
29                     33
...                   ...
19970                   1
19971                  14
19972                  19
19973                  13
19974                  10
19975                  22
19976                  20
19977                  18
19978                  23
19979                   2
19980                  23
19981                   0
19982                  11
19983                   8
19984                  29
19985                  26
19986                  13
19987                   1
19988                  33
19989                  19
19990                  33
19991                  13
19992                  31
19993                  25
19994                  23
19995                  29
19996                  10
19997                   1
19998                  24
19999                   0

[20000 rows x 1 columns]

In [816]:
label

array([ 7, 18, 18, ...,  1, 24,  0])

In [817]:
X_train,X_test,y_train,y_test=train_test_split(X,label,test_size=0.3,random_state=10)

In [818]:
X_train.shape
X_test[0]

array([89, 75, 73, 81, 72, 65, 81, 72, 92, 77.77777777777777,
       8.333333333333332, 66.66666666666666, 51.35135135135135,
       83.33333333333334, 53.84615384615385, 62.5], dtype=object)

In [819]:
X_train=pd.to_numeric(X_train[:,:].flatten())

In [820]:
X_train=X_train.reshape((14000,16))